# -*- coding: utf-8 -*-
"""Build a Movie Recommendation System in Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oeukJ3ktttEMp3H2LlcS8tBaH5IYppyn

####Pip install
"""

!pip install pandas

!pip install regex

!pip install scikit-learn

!pip install ipywidgets

"""####Data Prep

"""

# Import important libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re
from sklearn.feature_extraction.text import TfidfVectorizer # Tfidf matrix
from sklearn.metrics.pairwise import cosine_similarity # Cosine similarity
import ipywidgets as widgets
from IPython.display import display, clear_output

movies_df = pd.read_csv('movies.csv')

# Function to remove any character from title that is not a letter, didgit, or space.
def clean_title(title: str) -> str:
    title =  re.sub("[^a-zA-Z0-9 ]", "", title)
    return title

# Applying the clean_title function and creating clean_title column
movies_df['clean_title'] = movies_df['title'].apply(clean_title)
movies_df

# Creating Tfidf matrix
# Initializing the vectorize
vectorizer = TfidfVectorizer(ngram_range=(1,2))

# Creating the tfidf matrix
tfidf = vectorizer.fit_transform(movies_df['clean_title'])

tfidf.shape

"""####Cosine Similarity
- Cosine Similarity measures how "close" two documents are in terms of angles between their high-dimensional feature vectors- ignoring the lengths absolute legnths,
- A score of 1 means the vectors point in exactly the same direction.
- A score of 0 means they're unrelated
- A score of -1 means exactly opposite

"""

# Search function which returns the top n most similar movie titles in df to the given query string
def search(query, movies_df=movies_df, tfidf=tfidf, top_n=10):
    # Clean the query string
    q_clean = clean_title(query)
    # Vectorize the query string
    q_vec = vectorizer.transform([q_clean])

    # Compute cosine similarities
    similarity = cosine_similarity(q_vec, tfidf).flatten()

    # The top 10 indices
    top_idx = similarity.argsort()[-top_n:][::-1]

    # Return the top 5 movie titles
    results = movies_df.iloc[top_idx][['title']].copy()
    results['score'] = similarity[top_idx]
    return results

search('Avengers',movies_df,tfidf)

"""####Widget - Search bar
- Using ipywidgets
"""

# Input text
search_box = widgets.Text(
    value="",
    placeholder="Search...",
    description="Search:",
    layout=widgets.Layout(width="60%"),
    disabled=False
)

# Output
output_box = widgets.Output()

def on_search(change):
    with output_box:
        clear_output(wait=True)
        query = change['new'].strip()
        if query:
            results = search(query,movies_df,tfidf)
            display(results)


search_box.observe(on_search, names='value')

# Display the widgets
display(search_box, output_box)

"""####Ratings - second half of recommendation"""

ratings_df = pd.read_csv('ratings.csv')

ratings_df.head()

# Example movie id and movie we are using
movie_id = 89745
movie = movies_df[movies_df['movieId'] == movie_id]
movie

# Similar users
similar_users = (
    ratings_df
    .query("movieId == @movie_id and rating >= 4")
    ['userId']
    .unique()
)

n_sim = len(similar_users)
print(f"Found {n_sim} similar users.")

sub = ratings_df[
    (ratings_df.userId.isin(similar_users)) &
    (ratings_df.movieId != movie_id)

]

# For each movieId, count how many movies of similar users rated it >= 4
liked_counts = (
    sub[sub.rating >= 4]
    .groupby('movieId')['userId']
    .nunique()
)

rec_frac = liked_counts / n_sim

# drop the original movie if it slipped in
rec_frac = rec_frac.drop(index=movie_id, errors='ignore')

# keep only movies liked by >10% of these users
popular = rec_frac[rec_frac > 0.10].sort_values(ascending=False)

print(popular)

# List of recommendee movie IDs
rec_movies = popular.index.tolist()

# All users who rated any of these recommended movies >= 4
rating_rec = ratings_df[
    (ratings_df.movieId.isin(rec_movies)) &
    (ratings_df.rating >= 4)
]

users_who_rated = rating_rec.userId.unique()
print(f"Users who liked any recommended movies: {len(users_who_rated)}")

# Total number of unique users
total_users = ratings_df.userId.unique()
print(f"Total number of users: {len(total_users)}")

# For each recommended movie, count how many unique users liked it
user_counts = (
    rating_rec
    .groupby('movieId')
    .userId
    .nunique()
)

# The percentage of users who liked each movie
user_per = (user_counts / len(total_users)) * 100

rec_stats = user_per.to_frame(name='user_per') \
                        .sort_values('user_per', ascending=False)

print(rec_stats)

"""####Recommendation Score"""

similar_rec = rec_frac

all_rec = user_counts / len(total_users)

rec_per = pd.concat([similar_rec, all_rec], axis=1)
rec_per.columns = ['similar', 'all']

rec_per['score'] = rec_per['similar'] / rec_per['all']

rec_per = rec_per.sort_values('score', ascending=False)

# Top 10 movie recommendations
top10 = rec_per.head(10).reset_index().rename(columns={'index': 'movieId'})

top10 = top10.merge(movies_df[['movieId','title','genres']], on='movieId', how='left')

print(top10[['movieId','title','genres','similar','all','score']])

"""####Create a function - returns the top 10 recommendations"""

def recommend_niche(movie_id, ratings_df, movies_df,
                    like_threshold=4.0, min_frac=0.1, top_n=10):
    # 1) Who liked the target movie?
    sim_users = ratings_df.loc[
        (ratings_df['movieId'] == movie_id) &
        (ratings_df['rating']  >= like_threshold),
        'userId'
    ].unique()
    n_sim = len(sim_users)
    if n_sim == 0:
        return pd.DataFrame(columns=['score','title','genres'])

    # 2) Fraction of those users who liked each OTHER movie
    sub = ratings_df.loc[
        (ratings_df['userId'].isin(sim_users)) &
        (ratings_df['movieId'] != movie_id)
    ]
    sim_likes = sub.loc[
        sub['rating'] >= like_threshold
    ].groupby('movieId')['userId'].nunique()
    frac_sim = sim_likes / n_sim
    frac_sim = frac_sim[frac_sim >= min_frac]

    if frac_sim.empty:
        return pd.DataFrame(columns=['score','title','genres'])

    # 3) Fraction of ALL users who liked each movie
    total_users = ratings_df['userId'].nunique()
    all_likes = ratings_df.loc[
        ratings_df['rating'] >= like_threshold
    ].groupby('movieId')['userId'].nunique()
    frac_all  = all_likes / total_users

    # 4) Combine and compute the niche score
    rec_per = pd.concat(
        [frac_sim.rename('similar'), frac_all.rename('all')],
        axis=1, join='inner'
    ).dropna()
    rec_per['score'] = rec_per['similar'] / rec_per['all']

    # 5) Top‐N and merge titles+genres
    top = (
        rec_per
        .sort_values('score', ascending=False)
        .head(top_n)
        .reset_index()
        .rename(columns={'index':'movieId'})
    )
    top = top.merge(
        movies_df[['movieId','title','genres']],
        on='movieId',
        how='left'
    )

    return top[['score','title','genres']]

movie_id = 25058
results    = recommend_niche(movie_id, ratings_df, movies_df)
print(results)

"""####Interactive Recommendation System"""

import ipywidgets as widgets
from IPython.display import display, clear_output



search_box = widgets.Text(
    value='',
    placeholder='Type a movie title…',
    description='Search:',
    layout=widgets.Layout(width='70%')
)
output = widgets.Output()

def on_search_change(change):
    with output:
        clear_output()
        query = change['new'].strip()
        if not query:
            return

        # call your search function using exactly the names it needs:
        matches = search(query, movies_df, tfidf)
        if matches.empty:
            print("No matching titles found.")
            return

        movie_id = matches.index[0]
        title    = matches.iloc[0]['title']
        print(f"Top match: {title} (movieId={movie_id})\n")

        recs = recommend_niche(movie_id, ratings_df, movies_df)
        if recs.empty:
            print("No niche recommendations found.")
        else:
            display(recs)

search_box.observe(on_search_change, names='value')
display(search_box, output)